// @generated by protoc-gen-es v1.10.0
// @generated from file items/v1/items.proto (package items, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message items.GetBaseItemsRequest
 */
export const GetBaseItemsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "items.GetBaseItemsRequest",
  () => [
    { no: 1, name: "patchVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message items.GetBaseItemsResponse
 */
export const GetBaseItemsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "items.GetBaseItemsResponse",
  () => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "basic", kind: "message", T: Item },
    { no: 4, name: "data", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Item} },
  ],
);

/**
 * @generated from message items.GetItemImageByIdRequest
 */
export const GetItemImageByIdRequest = /*@__PURE__*/ proto3.makeMessageType(
  "items.GetItemImageByIdRequest",
  () => [
    { no: 1, name: "itemId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "patchVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message items.GetItemImageByIdResponse
 */
export const GetItemImageByIdResponse = /*@__PURE__*/ proto3.makeMessageType(
  "items.GetItemImageByIdResponse",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message items.GetItemInformationByIdRequest
 */
export const GetItemInformationByIdRequest = /*@__PURE__*/ proto3.makeMessageType(
  "items.GetItemInformationByIdRequest",
  () => [
    { no: 1, name: "patchVersion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "itemId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message items.GetItemInformationByIdResponse
 */
export const GetItemInformationByIdResponse = /*@__PURE__*/ proto3.makeMessageType(
  "items.GetItemInformationByIdResponse",
  () => [
    { no: 1, name: "item", kind: "message", T: Item },
  ],
);

/**
 * @generated from message items.Item
 */
export const Item = /*@__PURE__*/ proto3.makeMessageType(
  "items.Item",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "rune", kind: "message", T: Rune },
    { no: 3, name: "gold", kind: "message", T: Gold },
    { no: 4, name: "group", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "colloq", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "plaintext", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "consumed", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 9, name: "stacks", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "depth", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 11, name: "consumeOnFull", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 12, name: "specialRecipe", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 13, name: "inStore", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 14, name: "hideFromAll", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 15, name: "requiredChampion", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 16, name: "requiredAlly", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 17, name: "stats", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 2 /* ScalarType.FLOAT */} },
    { no: 18, name: "maps", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 8 /* ScalarType.BOOL */} },
    { no: 19, name: "tags", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 20, name: "effect", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ],
);

/**
 * @generated from message items.Gold
 */
export const Gold = /*@__PURE__*/ proto3.makeMessageType(
  "items.Gold",
  () => [
    { no: 1, name: "base", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "total", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "sell", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "purchasable", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message items.Rune
 */
export const Rune = /*@__PURE__*/ proto3.makeMessageType(
  "items.Rune",
  () => [
    { no: 1, name: "isrune", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "tier", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

