// @generated by protoc-gen-connect-es v1.6.1
// @generated from file items/v1/items.proto (package items, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetBaseItemsRequest, GetBaseItemsResponse, GetItemImageByIdRequest, GetItemImageByIdResponse, GetItemInformationByIdRequest, GetItemInformationByIdResponse } from "./items_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service items.ItemsService
 */
export declare const ItemsService: {
  readonly typeName: "items.ItemsService",
  readonly methods: {
    /**
     * @generated from rpc items.ItemsService.GetItemImageById
     */
    readonly getItemImageById: {
      readonly name: "GetItemImageById",
      readonly I: typeof GetItemImageByIdRequest,
      readonly O: typeof GetItemImageByIdResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc items.ItemsService.GetItemInformationById
     */
    readonly getItemInformationById: {
      readonly name: "GetItemInformationById",
      readonly I: typeof GetItemInformationByIdRequest,
      readonly O: typeof GetItemInformationByIdResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc items.ItemsService.GetBaseItems
     */
    readonly getBaseItems: {
      readonly name: "GetBaseItems",
      readonly I: typeof GetBaseItemsRequest,
      readonly O: typeof GetBaseItemsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

