// @generated by protoc-gen-connect-es v1.6.1
// @generated from file version/v1/version.proto (package version, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetCurrentVersionRequest, GetCurrentVersionResponse, GetVersionsRequest, GetVersionsResponse } from "./version_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service version.VersionService
 */
export declare const VersionService: {
  readonly typeName: "version.VersionService",
  readonly methods: {
    /**
     * @generated from rpc version.VersionService.GetVersions
     */
    readonly getVersions: {
      readonly name: "GetVersions",
      readonly I: typeof GetVersionsRequest,
      readonly O: typeof GetVersionsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc version.VersionService.GetCurrentVersion
     */
    readonly getCurrentVersion: {
      readonly name: "GetCurrentVersion",
      readonly I: typeof GetCurrentVersionRequest,
      readonly O: typeof GetCurrentVersionResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

