// @generated by protoc-gen-es v1.10.0
// @generated from file version/v1/version.proto (package version, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message version.GetVersionsRequest
 */
export declare class GetVersionsRequest extends Message<GetVersionsRequest> {
  constructor(data?: PartialMessage<GetVersionsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "version.GetVersionsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetVersionsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetVersionsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetVersionsRequest;

  static equals(a: GetVersionsRequest | PlainMessage<GetVersionsRequest> | undefined, b: GetVersionsRequest | PlainMessage<GetVersionsRequest> | undefined): boolean;
}

/**
 * @generated from message version.GetVersionsResponse
 */
export declare class GetVersionsResponse extends Message<GetVersionsResponse> {
  /**
   * @generated from field: repeated string versions = 1;
   */
  versions: string[];

  constructor(data?: PartialMessage<GetVersionsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "version.GetVersionsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetVersionsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetVersionsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetVersionsResponse;

  static equals(a: GetVersionsResponse | PlainMessage<GetVersionsResponse> | undefined, b: GetVersionsResponse | PlainMessage<GetVersionsResponse> | undefined): boolean;
}

/**
 * @generated from message version.GetCurrentVersionRequest
 */
export declare class GetCurrentVersionRequest extends Message<GetCurrentVersionRequest> {
  constructor(data?: PartialMessage<GetCurrentVersionRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "version.GetCurrentVersionRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCurrentVersionRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCurrentVersionRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCurrentVersionRequest;

  static equals(a: GetCurrentVersionRequest | PlainMessage<GetCurrentVersionRequest> | undefined, b: GetCurrentVersionRequest | PlainMessage<GetCurrentVersionRequest> | undefined): boolean;
}

/**
 * @generated from message version.GetCurrentVersionResponse
 */
export declare class GetCurrentVersionResponse extends Message<GetCurrentVersionResponse> {
  /**
   * @generated from field: string version = 1;
   */
  version: string;

  constructor(data?: PartialMessage<GetCurrentVersionResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "version.GetCurrentVersionResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetCurrentVersionResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetCurrentVersionResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetCurrentVersionResponse;

  static equals(a: GetCurrentVersionResponse | PlainMessage<GetCurrentVersionResponse> | undefined, b: GetCurrentVersionResponse | PlainMessage<GetCurrentVersionResponse> | undefined): boolean;
}

